### PR TITLE
Adding BroadcastEloquentEvents Trait

### PR DESCRIPTION
**Pull request by matthewhall-ca**
A trait that can be added to any model to automatically broadcast events in a consistent manner

### CODE REVIEW

**Comment by masterjus** [comment]
@matthewhall-ca please fix code style issues and make some tests

**Comment by matthewhall-ca** [comment]
@masterjus  any suggestions for how to test the trait? Been trying to come up with a clean way to do it. May need to setup something like

https://github.com/dwightwatson/validating/blob/master/tests/ValidatingObserverTest.php

**Comment by masterjus** [comment]
you can create stub model within test which is using this trait. You don't need to test how Laravel calls observer. You need to test that only available were registered.

**Comment by masterjus** [comment]
@matthewhall-ca https://github.com/nuwber/rabbitevents/pull/23

**Pull request closed without merging**
